### ISSUE TITLE
Ruby error on running `doing meanwhile`

### ISSUE THREAD

**Issue by mhairston** [ttscoff/doing#110]
Whenever I try to run `meanwhile`, I get this error:

```
add_item': undefined method `join' for "":String (NoMethodError)`
```

* Happens under Ruby 2.6.3, 2.6.5, and 2.7.1.
* I installed doing less than a week ago, without sudo. Also tried the --pre install.
* Tried renaming my what-was-I-doing file out of the way and starting with a fresh one, still get the error.
* Found a similar issue (closed), but it's a different error: <https://github.com/ttscoff/doing/issues/103>

Traceback:
```
	11: from /Users/mhairston/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
	10: from /Users/mhairston/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
	 9: from /Users/mhairston/.rvm/gems/ruby-2.7.1/bin/doing:23:in `<main>'
	 8: from /Users/mhairston/.rvm/gems/ruby-2.7.1/bin/doing:23:in `load'
	 7: from /Users/mhairston/.rvm/gems/ruby-2.7.1/gems/doing-1.0.33/bin/doing:1165:in `<top (required)>'
	 6: from /Users/mhairston/.rvm/gems/ruby-2.7.1/gems/gli-2.19.2/lib/gli/app_support.rb:83:in `run'
	 5: from /Users/mhairston/.rvm/gems/ruby-2.7.1/gems/gli-2.19.2/lib/gli/app_support.rb:309:in `call_command'
	 4: from /Users/mhairston/.rvm/gems/ruby-2.7.1/gems/gli-2.19.2/lib/gli/app_support.rb:296:in `block in call_command'
	 3: from /Users/mhairston/.rvm/gems/ruby-2.7.1/gems/gli-2.19.2/lib/gli/command_support.rb:131:in `execute'
	 2: from /Users/mhairston/.rvm/gems/ruby-2.7.1/gems/doing-1.0.33/bin/doing:241:in `block (2 levels) in <top (required)>'
	 1: from /Users/mhairston/.rvm/gems/ruby-2.7.1/gems/doing-1.0.33/lib/doing/wwid.rb:878:in `stop_start'
/Users/mhairston/.rvm/gems/ruby-2.7.1/gems/doing-1.0.33/lib/doing/wwid.rb:604:in `add_item': undefined method `join' for "":String (NoMethodError)
```

**Comment by ttscoff** [comment]
Pushed v1.0.34 to gem, try updating with `gem update doing` and see if 
it fixes the issue for you.

-Brett

**Comment by mhairston** [comment]
That fixes it, thanks!
