### ISSUE TITLE
Require cannot load such file

### ISSUE THREAD

**Issue by krzysiek-b** [ttscoff/doing#151]
**Describe the bug**

Latest version 2.1.54 throws error

```
Traceback (most recent call last):
        4: from /usr/local/bin/doing:23:in `<main>'
        3: from /usr/local/bin/doing:23:in `load'
        2: from /var/lib/gems/2.7.0/gems/doing-2.1.54/bin/doing:6:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- doing/help_monkey_patch (LoadError)
```

Is this anything you already know and have fixed?

**Comment by ttscoff** [comment]
Known issue affecting people who install using `sudo`. I think I have it 
repaired in 2.1.55, let me know if that works for you.

**Comment by krzysiek-b** [comment]
Hi, this seems to be fixed.
