### ISSUE TITLE
Crashing: "undefined method `[]' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by iandundas** [ttscoff/doing#36]
Opening an issue as I'm currently getting the following problem, no matter what parameters I give to Doing. I'll update with a fix if I find one.

```
/Users/ian/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/doing-0.2.4/lib/doing/wwid.rb:103:in `block in initialize': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/ian/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/doing-0.2.4/lib/doing/wwid.rb:92:in `each'
    from /Users/ian/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/doing-0.2.4/lib/doing/wwid.rb:92:in `initialize'
    from /Users/ian/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/doing-0.2.4/bin/doing:14:in `new'
    from /Users/ian/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/doing-0.2.4/bin/doing:14:in `<top (required)>'
    from /Users/ian/.rbenv/versions/2.0.0-p247/bin/doing:23:in `load'
    from /Users/ian/.rbenv/versions/2.0.0-p247/bin/doing:23:in `<main>'
```

**Comment by RobTrew** [comment]
Do have a `~/.doingrc` file here (minimally configured to name an output file path)
```
> doing now hello world
```

--> `error: undefined method `[]' for nil:NilClass`

Any thoughts ?

**Comment by ttscoff** [comment]
Hi Rob,

See #58

**Comment by RobTrew** [comment]
Got it – thanks !
