### ISSUE TITLE
Doesn't work on Windows because code assumes `uname` command exists

### ISSUE THREAD

**Issue by bentsai** [ttscoff/doing#71]
The `uname` command does not exist on Windows, so the `doing` script fails with all the checks that were added in the code for "Darwin". 

```
$ doing config
C:/bin/ruby21/lib/ruby/gems/2.1.0/gems/doing-1.0.8pre/bin/doing:983:in ``': No such file or directory - uname (Errno::ENOENT)
        from C:/bin/ruby21/lib/ruby/gems/2.1.0/gems/doing-1.0.8pre/bin/doing:983:in `block in <top (required)>'
        from C:/bin/ruby21/lib/ruby/gems/2.1.0/gems/gli-2.9.0/lib/gli/dsl.rb:177:in `command'
        from C:/bin/ruby21/lib/ruby/gems/2.1.0/gems/doing-1.0.8pre/bin/doing:978:in `<top (required)>'
        from C:/bin/ruby21/bin/doing:23:in `load'
        from C:/bin/ruby21/bin/doing:23:in `<main>'
```

This bug was introduced by https://github.com/ttscoff/doing/commit/eed257d24fabe167a56a110a310134eb5921b4ac and can probably fixed by using https://rubygems.org/gems/sys-uname instead of relying on the Unix command.

**Comment by ttscoff** [comment]
I know it took me 7 years to close this ticket, but I've switched `uname` to sys-uname and it seems to be working fine. Will be in version 2.1.30 (next release).

**Comment by androbytes** [comment]
I've got this error just now:
```
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/doing-2.1.86/bin/commands/config.rb:48:in ``': No such file or directory - uname (Errno::ENOENT)
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/doing-2.1.86/bin/commands/config.rb:48:in `block (2 levels) in <top (required)>'```
